import { phetPhase3Simulations } from "./phetPhase3Catalog.js";

export const phetSubjectGroups = [
  {
    id: "physics",
    label: "物理",
    topics: [
      { id: "motion", label: "运动" },
      { id: "waves", label: "声音、振动、波" },
      { id: "work-energy-power", label: "功、能量、功率" },
      { id: "heat", label: "热学" },
      { id: "quantum-phenomena", label: "量子现象" },
      { id: "light-radiation", label: "光和辐射" },
      { id: "electricity-magnetism-circuits", label: "电场、磁场、电路" },
    ],
  },
  {
    id: "math",
    label: "数学",
    topics: [
      { id: "math-concepts", label: "数学概念" },
      { id: "math-applications", label: "数学的应用" },
    ],
  },
  {
    id: "chemistry",
    label: "化学",
    topics: [
      { id: "general-chemistry", label: "普通化学" },
      { id: "quantum-chemistry", label: "量子化学" },
    ],
  },
  {
    id: "earth-science",
    label: "地球科学",
    topics: [],
  },
  {
    id: "biology",
    label: "生物",
    topics: [],
  },
];

export const phetSchoolStages = [
  { id: "primary", label: "小学" },
  { id: "middle", label: "初中" },
  { id: "high", label: "高中" },
];

export const phetSimulations = [
  {
    id: "waves-intro",
    title: "波动入门",
    description: "通过水波、声波和光波观察频率与振幅的作用。",
    subject: "physics",
    topics: ["waves"],
    stages: ["primary", "middle"],
    localUrl: "/simulations/phet/waves-intro.html?locale=zh_CN",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/waves-intro",
    sourceUrl: "https://phet.colorado.edu/sims/html/waves-intro/latest/waves-intro_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "forces-and-motion-basics",
    title: "力和运动：基础",
    description: "通过拔河和推动物体探索力、摩擦与运动的关系。",
    subject: "physics",
    topics: ["motion"],
    stages: ["primary", "middle", "high"],
    localUrl: "/simulations/phet/forces-and-motion-basics.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/forces-and-motion-basics",
    sourceUrl: "https://phet.colorado.edu/sims/html/forces-and-motion-basics/latest/forces-and-motion-basics_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "projectile-motion",
    title: "斜抛运动",
    description: "改变发射角度、速度和空气阻力，观察抛体运动轨迹。",
    subject: "physics",
    topics: ["motion"],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/projectile-motion.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/projectile-motion",
    sourceUrl: "https://phet.colorado.edu/sims/html/projectile-motion/latest/projectile-motion_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "energy-skate-park",
    title: "能量滑板竞技场",
    description: "建造滑板轨道，观察动能、势能、热能与摩擦的变化。",
    subject: "physics",
    topics: ["work-energy-power"],
    stages: ["high"],
    localUrl: "/simulations/phet/energy-skate-park.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/energy-skate-park",
    sourceUrl: "https://phet.colorado.edu/sims/html/energy-skate-park/latest/energy-skate-park_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "masses-and-springs",
    title: "质量和弹簧",
    description: "改变质量、弹簧劲度和阻尼，研究振动、周期、力与能量。",
    subject: "physics",
    topics: ["motion", "work-energy-power"],
    stages: ["high"],
    localUrl: "/simulations/phet/masses-and-springs.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/masses-and-springs",
    sourceUrl: "https://phet.colorado.edu/sims/html/masses-and-springs/latest/masses-and-springs_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "pendulum-lab",
    title: "钟摆实验",
    description: "改变摆长、质量、重力和振幅，测量周期并观察能量变化。",
    subject: "physics",
    topics: ["motion", "work-energy-power"],
    stages: ["primary", "middle", "high"],
    localUrl: "/simulations/phet/pendulum-lab.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/pendulum-lab",
    sourceUrl: "https://phet.colorado.edu/sims/html/pendulum-lab/latest/pendulum-lab_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "states-of-matter-basics",
    title: "物质状态：基础",
    description: "加热、冷却和压缩粒子，观察固态、液态和气态的转变。",
    subject: "physics",
    topics: ["heat"],
    stages: ["primary", "middle", "high"],
    localUrl: "/simulations/phet/states-of-matter-basics.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/states-of-matter-basics",
    sourceUrl: "https://phet.colorado.edu/sims/html/states-of-matter-basics/latest/states-of-matter-basics_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "circuit-construction-kit-dc",
    title: "电路组建实验：直流",
    description: "搭建直流电路，使用电流表和电压表观察电路规律。",
    subject: "physics",
    topics: ["electricity-magnetism-circuits"],
    stages: ["primary", "middle", "high"],
    localUrl: "/simulations/phet/circuit-construction-kit-dc.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/circuit-construction-kit-dc",
    sourceUrl: "https://phet.colorado.edu/sims/html/circuit-construction-kit-dc/latest/circuit-construction-kit-dc_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "balloons-and-static-electricity",
    title: "气球和静电",
    description: "用气球探索电荷转移、静电吸引、排斥和电荷极化。",
    subject: "physics",
    topics: ["electricity-magnetism-circuits"],
    stages: ["primary", "middle", "high"],
    localUrl: "/simulations/phet/balloons-and-static-electricity.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/balloons-and-static-electricity",
    sourceUrl: "https://phet.colorado.edu/sims/html/balloons-and-static-electricity/latest/balloons-and-static-electricity_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "bending-light",
    title: "光的折射",
    description: "观察光在不同介质中的折射，使用棱镜探索色散和彩虹。",
    subject: "physics",
    topics: ["light-radiation"],
    stages: ["primary", "middle", "high"],
    localUrl: "/simulations/phet/bending-light.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/bending-light",
    sourceUrl: "https://phet.colorado.edu/sims/html/bending-light/latest/bending-light_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "color-vision",
    title: "光的混合",
    description: "混合红、绿、蓝光，观察波长、白光和颜色视觉的关系。",
    subject: "physics",
    topics: ["light-radiation"],
    stages: ["primary", "middle", "high"],
    localUrl: "/simulations/phet/color-vision.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/color-vision",
    sourceUrl: "https://phet.colorado.edu/sims/html/color-vision/latest/color-vision_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "john-travoltage",
    title: "静电电压",
    description: "通过日常场景观察静电积累、放电和人体受到电击的条件。",
    subject: "physics",
    topics: ["electricity-magnetism-circuits"],
    stages: ["primary", "middle", "high"],
    localUrl: "/simulations/phet/john-travoltage.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/john-travoltage",
    sourceUrl: "https://phet.colorado.edu/sims/html/john-travoltage/latest/john-travoltage_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "wave-interference",
    title: "波的干涉",
    description: "使用水波、声波和光波观察干涉、单缝衍射与双缝干涉。",
    subject: "physics",
    subjects: ["physics", "earth-science"],
    topics: ["waves", "light-radiation"],
    stages: ["primary", "middle", "high"],
    localUrl: "/simulations/phet/wave-interference.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/wave-interference",
    sourceUrl: "https://phet.colorado.edu/sims/html/wave-interference/latest/wave-interference_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "fractions-intro",
    title: "分数：入门",
    description: "通过图形、数值和游戏建立分数的基本概念。",
    subject: "math",
    topics: ["math-concepts"],
    stages: ["primary", "middle"],
    localUrl: "/simulations/phet/fractions-intro.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/fractions-intro",
    sourceUrl: "https://phet.colorado.edu/sims/html/fractions-intro/latest/fractions-intro_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "fractions-equality",
    title: "分数：等式",
    description: "使用不同分母构建等值分数，并通过图形和数字进行匹配。",
    subject: "math",
    topics: ["math-concepts"],
    stages: ["primary", "middle"],
    localUrl: "/simulations/phet/fractions-equality.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/fractions-equality",
    sourceUrl: "https://phet.colorado.edu/sims/html/fractions-equality/latest/fractions-equality_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "fractions-mixed-numbers",
    title: "分数：带分数",
    description: "使用图形和数字理解假分数、带分数及其相互转换。",
    subject: "math",
    topics: ["math-concepts"],
    stages: ["primary", "middle"],
    localUrl: "/simulations/phet/fractions-mixed-numbers.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/fractions-mixed-numbers",
    sourceUrl: "https://phet.colorado.edu/sims/html/fractions-mixed-numbers/latest/fractions-mixed-numbers_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "area-model-introduction",
    title: "面积模型入门",
    description: "构造不同尺寸的长方形，用面积模型理解乘法。",
    subject: "math",
    topics: ["math-concepts"],
    stages: ["primary"],
    localUrl: "/simulations/phet/area-model-introduction.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/area-model-introduction",
    sourceUrl: "https://phet.colorado.edu/sims/html/area-model-introduction/latest/area-model-introduction_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "number-line-operations",
    title: "数轴：运算",
    description: "在数轴上表示和计算正负数运算，观察位置与方向的变化。",
    subject: "math",
    topics: ["math-concepts"],
    stages: ["middle"],
    localUrl: "/simulations/phet/number-line-operations.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/number-line-operations",
    sourceUrl: "https://phet.colorado.edu/sims/html/number-line-operations/latest/number-line-operations_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "graphing-lines",
    title: "直线图形",
    description: "探索直线、斜率、截距、线性方程和图像之间的关系。",
    subject: "math",
    topics: ["math-applications"],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/graphing-lines.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/graphing-lines",
    sourceUrl: "https://phet.colorado.edu/sims/html/graphing-lines/latest/graphing-lines_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "build-an-atom",
    title: "原子模型",
    description: "使用质子、中子和电子构建原子，观察元素、电荷和质量变化。",
    subject: "chemistry",
    topics: ["general-chemistry"],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/build-an-atom.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/build-an-atom",
    sourceUrl: "https://phet.colorado.edu/sims/html/build-an-atom/latest/build-an-atom_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "balancing-chemical-equations",
    title: "配平化学方程式",
    description: "通过粒子模型和游戏理解并练习化学方程式配平。",
    subject: "chemistry",
    topics: ["general-chemistry"],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/balancing-chemical-equations.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/balancing-chemical-equations",
    sourceUrl: "https://phet.colorado.edu/sims/html/balancing-chemical-equations/latest/balancing-chemical-equations_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "molecule-shapes",
    title: "分子形状",
    description: "构建三维分子，探索化学键、孤对电子和分子空间结构。",
    subject: "chemistry",
    topics: ["general-chemistry"],
    stages: ["high"],
    localUrl: "/simulations/phet/molecule-shapes.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/molecule-shapes",
    sourceUrl: "https://phet.colorado.edu/sims/html/molecule-shapes/latest/molecule-shapes_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "concentration",
    title: "浓度",
    description: "改变溶质、水量和蒸发程度，观察并测量溶液浓度。",
    subject: "chemistry",
    topics: ["general-chemistry"],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/concentration.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/concentration",
    sourceUrl: "https://phet.colorado.edu/sims/html/concentration/latest/concentration_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "acid-base-solutions",
    title: "酸碱溶液",
    description: "测量溶液pH值和导电性，比较强弱酸碱及浓度的影响。",
    subject: "chemistry",
    topics: ["general-chemistry"],
    stages: ["high"],
    localUrl: "/simulations/phet/acid-base-solutions.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/acid-base-solutions",
    sourceUrl: "https://phet.colorado.edu/sims/html/acid-base-solutions/latest/acid-base-solutions_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "ph-scale",
    title: "pH值",
    description: "测试常见液体的pH值，观察酸碱性、稀释与离子数量变化。",
    subject: "chemistry",
    topics: ["general-chemistry"],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/ph-scale.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/ph-scale",
    sourceUrl: "https://phet.colorado.edu/sims/html/ph-scale/latest/ph-scale_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "natural-selection",
    title: "自然选择",
    description: "控制环境和兔子的遗传变异，探索自然选择规律。",
    subject: "biology",
    topics: [],
    stages: ["primary", "middle", "high"],
    localUrl: "/simulations/phet/natural-selection.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/natural-selection",
    sourceUrl: "https://phet.colorado.edu/sims/html/natural-selection/latest/natural-selection_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "gene-expression-essentials",
    title: "基因表达基础",
    description: "观察蛋白质合成过程，探索影响细胞基因表达的因素。",
    subject: "biology",
    topics: [],
    stages: ["high"],
    localUrl: "/simulations/phet/gene-expression-essentials.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/gene-expression-essentials",
    sourceUrl: "https://phet.colorado.edu/sims/html/gene-expression-essentials/latest/gene-expression-essentials_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "gravity-and-orbits",
    title: "重力和轨道",
    description: "移动太阳、地球、月球和空间站，观察引力与轨道变化。",
    subject: "earth-science",
    topics: [],
    stages: ["primary", "middle", "high"],
    localUrl: "/simulations/phet/gravity-and-orbits.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/gravity-and-orbits",
    sourceUrl: "https://phet.colorado.edu/sims/html/gravity-and-orbits/latest/gravity-and-orbits_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "density",
    title: "密度",
    description: "改变质量和体积，测量物体密度并探索浮沉现象。",
    subject: "earth-science",
    topics: [],
    stages: ["primary", "middle"],
    localUrl: "/simulations/phet/density.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/density",
    sourceUrl: "https://phet.colorado.edu/sims/html/density/latest/density_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "under-pressure",
    title: "受到压力",
    description: "观察液体深度、重力、容器形状和密度对压力的影响。",
    subject: "earth-science",
    topics: [],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/under-pressure.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/under-pressure",
    sourceUrl: "https://phet.colorado.edu/sims/html/under-pressure/latest/under-pressure_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "friction",
    title: "摩擦力",
    description: "观察不同表面之间的摩擦、微观作用与温度变化。",
    subject: "physics",
    topics: ["motion"],
    stages: ["primary", "middle", "high"],
    localUrl: "/simulations/phet/friction.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/friction",
    sourceUrl: "https://phet.colorado.edu/sims/html/friction/latest/friction_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  {
    id: "balancing-act",
    title: "平衡游戏",
    description: "移动物体探索力矩、质量、距离与杠杆平衡的关系。",
    subject: "physics",
    topics: ["motion"],
    stages: ["primary", "middle"],
    localUrl: "/simulations/phet/balancing-act.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/balancing-act",
    sourceUrl: "https://phet.colorado.edu/sims/html/balancing-act/latest/balancing-act_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  {
    id: "energy-skate-park-basics",
    title: "能量滑板竞技场：基础",
    description: "通过滑板轨道直观观察动能、势能、热能和能量守恒。",
    subject: "physics",
    topics: ["work-energy-power"],
    stages: ["primary", "middle"],
    localUrl: "/simulations/phet/energy-skate-park-basics.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/energy-skate-park-basics",
    sourceUrl: "https://phet.colorado.edu/sims/html/energy-skate-park-basics/latest/energy-skate-park-basics_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  {
    id: "gravity-force-lab-basics",
    title: "万有引力实验室：基础",
    description: "改变质量和距离，观察两个物体之间万有引力的变化。",
    subject: "physics",
    topics: ["motion"],
    stages: ["primary", "middle"],
    localUrl: "/simulations/phet/gravity-force-lab-basics.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/gravity-force-lab-basics",
    sourceUrl: "https://phet.colorado.edu/sims/html/gravity-force-lab-basics/latest/gravity-force-lab-basics_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  {
    id: "collision-lab",
    title: "碰撞实验室",
    description: "设置物体质量和速度，研究动量、动能与碰撞过程。",
    subject: "physics",
    topics: ["motion", "work-energy-power"],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/collision-lab.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/collision-lab",
    sourceUrl: "https://phet.colorado.edu/sims/html/collision-lab/latest/collision-lab_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  {
    id: "hookes-law",
    title: "胡克定律",
    description: "改变弹簧和外力，探索形变量、弹性势能与胡克定律。",
    subject: "physics",
    topics: ["motion", "work-energy-power"],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/hookes-law.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/hookes-law",
    sourceUrl: "https://phet.colorado.edu/sims/html/hookes-law/latest/hookes-law_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  {
    id: "energy-forms-and-changes",
    title: "能量形式和转换",
    description: "观察机械能、热能、电能和光能之间的传递与转换。",
    subject: "physics",
    topics: ["work-energy-power", "heat"],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/energy-forms-and-changes.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/energy-forms-and-changes",
    sourceUrl: "https://phet.colorado.edu/sims/html/energy-forms-and-changes/latest/energy-forms-and-changes_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  {
    id: "gas-properties",
    title: "气体性质",
    description: "改变温度、体积和粒子数量，研究气体压强与状态变化。",
    subject: "physics",
    topics: ["heat"],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/gas-properties.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/gas-properties",
    sourceUrl: "https://phet.colorado.edu/sims/html/gas-properties/latest/gas-properties_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  {
    id: "wave-on-a-string",
    title: "弦上的波",
    description: "改变振幅、频率、张力和阻尼，观察波在弦上的传播。",
    subject: "physics",
    topics: ["waves"],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/wave-on-a-string.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/wave-on-a-string",
    sourceUrl: "https://phet.colorado.edu/sims/html/wave-on-a-string/latest/wave-on-a-string_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  {
    id: "geometric-optics",
    title: "几何光学",
    description: "移动物体和透镜，观察成像位置、大小、方向与光线路径。",
    subject: "physics",
    topics: ["light-radiation"],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/geometric-optics.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/geometric-optics",
    sourceUrl: "https://phet.colorado.edu/sims/html/geometric-optics/latest/geometric-optics_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  {
    id: "charges-and-fields",
    title: "电荷与电场",
    description: "放置正负电荷，观察电场方向、电势和等势线分布。",
    subject: "physics",
    topics: ["electricity-magnetism-circuits"],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/charges-and-fields.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/charges-and-fields",
    sourceUrl: "https://phet.colorado.edu/sims/html/charges-and-fields/latest/charges-and-fields_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  {
    id: "coulombs-law",
    title: "库仑定律",
    description: "改变电荷量和距离，测量静电力并验证库仑定律。",
    subject: "physics",
    topics: ["electricity-magnetism-circuits"],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/coulombs-law.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/coulombs-law",
    sourceUrl: "https://phet.colorado.edu/sims/html/coulombs-law/latest/coulombs-law_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  {
    id: "resistance-in-a-wire",
    title: "导线电阻",
    description: "改变导线长度、横截面积和电阻率，观察电阻变化。",
    subject: "physics",
    topics: ["electricity-magnetism-circuits"],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/resistance-in-a-wire.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/resistance-in-a-wire",
    sourceUrl: "https://phet.colorado.edu/sims/html/resistance-in-a-wire/latest/resistance-in-a-wire_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  {
    id: "ohms-law",
    title: "欧姆定律",
    description: "调节电压和电阻，观察电流变化并理解欧姆定律。",
    subject: "physics",
    topics: ["electricity-magnetism-circuits"],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/ohms-law.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/ohms-law",
    sourceUrl: "https://phet.colorado.edu/sims/html/ohms-law/latest/ohms-law_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  {
    id: "faradays-law",
    title: "法拉第定律",
    description: "移动磁铁和线圈，观察磁通量变化与感应电流。",
    subject: "physics",
    topics: ["electricity-magnetism-circuits"],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/faradays-law.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/faradays-law",
    sourceUrl: "https://phet.colorado.edu/sims/html/faradays-law/latest/faradays-law_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  {
    id: "capacitor-lab-basics",
    title: "电容器实验室：基础",
    description: "改变极板面积、间距和电压，研究电容与储能。",
    subject: "physics",
    topics: ["electricity-magnetism-circuits"],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/capacitor-lab-basics.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/capacitor-lab-basics",
    sourceUrl: "https://phet.colorado.edu/sims/html/capacitor-lab-basics/latest/capacitor-lab-basics_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  {
    id: "blackbody-spectrum",
    title: "黑体光谱",
    description: "改变物体温度，观察热辐射光谱、峰值波长与颜色变化。",
    subject: "physics",
    topics: ["heat", "light-radiation", "quantum-phenomena"],
    stages: ["high"],
    localUrl: "/simulations/phet/blackbody-spectrum.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/blackbody-spectrum",
    sourceUrl: "https://phet.colorado.edu/sims/html/blackbody-spectrum/latest/blackbody-spectrum_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  {
    id: "rutherford-scattering",
    title: "卢瑟福散射",
    description: "发射阿尔法粒子，探索原子核结构与卢瑟福散射实验。",
    subject: "physics",
    topics: ["quantum-phenomena"],
    stages: ["high"],
    localUrl: "/simulations/phet/rutherford-scattering.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/rutherford-scattering",
    sourceUrl: "https://phet.colorado.edu/sims/html/rutherford-scattering/latest/rutherford-scattering_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  {
    id: "arithmetic",
    title: "算术",
    description: "通过图形和数字练习乘法、除法与因数关系。",
    subject: "math",
    topics: ["math-concepts"],
    stages: ["primary", "middle"],
    localUrl: "/simulations/phet/arithmetic.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/arithmetic",
    sourceUrl: "https://phet.colorado.edu/sims/html/arithmetic/latest/arithmetic_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  {
    id: "make-a-ten",
    title: "凑十",
    description: "组合数字建立十进制数感，练习加减与位值概念。",
    subject: "math",
    topics: ["math-concepts"],
    stages: ["primary"],
    localUrl: "/simulations/phet/make-a-ten.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/make-a-ten",
    sourceUrl: "https://phet.colorado.edu/sims/html/make-a-ten/latest/make-a-ten_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  {
    id: "number-play",
    title: "数字游戏",
    description: "使用数字、物体和数轴建立数量、位值与运算直觉。",
    subject: "math",
    topics: ["math-concepts"],
    stages: ["primary"],
    localUrl: "/simulations/phet/number-play.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/number-play",
    sourceUrl: "https://phet.colorado.edu/sims/html/number-play/latest/number-play_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  {
    id: "equality-explorer",
    title: "等式探究",
    description: "保持天平两边相等，探索等式变形和未知数求解。",
    subject: "math",
    topics: ["math-concepts", "math-applications"],
    stages: ["middle"],
    localUrl: "/simulations/phet/equality-explorer.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/equality-explorer",
    sourceUrl: "https://phet.colorado.edu/sims/html/equality-explorer/latest/equality-explorer_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  {
    id: "function-builder-basics",
    title: "函数构建器：基础",
    description: "通过输入和输出关系理解函数规则、表示和组合。",
    subject: "math",
    topics: ["math-applications"],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/function-builder-basics.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/function-builder-basics",
    sourceUrl: "https://phet.colorado.edu/sims/html/function-builder-basics/latest/function-builder-basics_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  {
    id: "graphing-quadratics",
    title: "二次函数图像",
    description: "改变二次函数参数，观察抛物线顶点、开口和交点变化。",
    subject: "math",
    topics: ["math-applications"],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/graphing-quadratics.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/graphing-quadratics",
    sourceUrl: "https://phet.colorado.edu/sims/html/graphing-quadratics/latest/graphing-quadratics_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  {
    id: "molecule-polarity",
    title: "分子极性",
    description: "改变原子电负性和分子形状，研究键极性与分子极性。",
    subject: "chemistry",
    topics: ["general-chemistry"],
    stages: ["high"],
    localUrl: "/simulations/phet/molecule-polarity.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/molecule-polarity",
    sourceUrl: "https://phet.colorado.edu/sims/html/molecule-polarity/latest/molecule-polarity_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  {
    id: "reactants-products-and-leftovers",
    title: "反应物、生成物与剩余物",
    description: "组合反应物并比较生成物，理解限量试剂和剩余物。",
    subject: "chemistry",
    topics: ["general-chemistry"],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/reactants-products-and-leftovers.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/reactants-products-and-leftovers",
    sourceUrl: "https://phet.colorado.edu/sims/html/reactants-products-and-leftovers/latest/reactants-products-and-leftovers_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  {
    id: "beers-law-lab",
    title: "比尔定律实验室",
    description: "调节溶液浓度和光程，研究吸光度、透光率与比尔定律。",
    subject: "chemistry",
    topics: ["general-chemistry"],
    stages: ["high"],
    localUrl: "/simulations/phet/beers-law-lab.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/beers-law-lab",
    sourceUrl: "https://phet.colorado.edu/sims/html/beers-law-lab/latest/beers-law-lab_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  {
    id: "molarity",
    title: "摩尔浓度",
    description: "改变溶质和溶液体积，观察摩尔浓度及饱和状态。",
    subject: "chemistry",
    topics: ["general-chemistry"],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/molarity.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/molarity",
    sourceUrl: "https://phet.colorado.edu/sims/html/molarity/latest/molarity_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  {
    id: "isotopes-and-atomic-mass",
    title: "同位素与原子质量",
    description: "组合不同同位素，计算平均原子质量并理解丰度影响。",
    subject: "chemistry",
    topics: ["general-chemistry", "quantum-chemistry"],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/isotopes-and-atomic-mass.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/isotopes-and-atomic-mass",
    sourceUrl: "https://phet.colorado.edu/sims/html/isotopes-and-atomic-mass/latest/isotopes-and-atomic-mass_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  {
    id: "neuron",
    title: "神经元",
    description: "刺激神经元并观察离子运动、膜电位和动作电位传播。",
    subject: "biology",
    topics: [],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/neuron.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/neuron",
    sourceUrl: "https://phet.colorado.edu/sims/html/neuron/latest/neuron_zh_CN.html",
    batch: "phase2",
    available: true,
  },
  ...phetPhase3Simulations,
];
