const phase3Rows = [
  ["number-compare", "数字比较", "比较数字大小，并用多种表示方式建立数量关系。", "math", ["math-concepts"], ["primary"]],
  ["area-builder", "区域建造者", "用方格搭建图形，探索面积、周长和分解组合。", "math", ["math-concepts"], ["primary", "middle"]],
  ["area-model-decimals", "面积模型：小数", "用面积模型理解小数乘法、位值和部分与整体。", "math", ["math-concepts"], ["primary", "middle"]],
  ["area-model-multiplication", "面积模型乘法", "拆分因数并使用面积模型理解多位数乘法。", "math", ["math-concepts"], ["primary", "middle"]],
  ["build-a-fraction", "构建一个分数", "通过图形和数字构建分数，理解等值与大小关系。", "math", ["math-concepts"], ["primary", "middle"]],
  ["equality-explorer-basics", "等式探索：基础", "借助平衡模型理解等号含义和基本等式变换。", "math", ["math-concepts"], ["primary", "middle"]],
  ["gases-intro", "气体基础", "改变容器、温度和粒子数量，观察气体压强变化。", "physics", ["heat"], ["primary", "middle"]],
  ["masses-and-springs-basics", "质量与弹簧：基础", "悬挂不同质量，观察弹簧伸长、平衡和振动。", "physics", ["motion", "work-energy-power"], ["primary", "middle"]],
  ["number-line-integers", "数轴：整数", "在数轴上表示正负数，练习比较、方向和变化。", "math", ["math-concepts"], ["primary", "middle"]],
  ["proportion-playground", "比例游乐场", "调整图形、颜色和数量，直观探索比例关系。", "math", ["math-concepts", "math-applications"], ["primary", "middle"]],
  ["ratio-and-proportion", "比率和比例", "通过可视模型理解比率、比例和等比例变化。", "math", ["math-concepts", "math-applications"], ["primary", "middle"]],
  ["expression-exchange", "表达式变换", "组合与交换代数表达式，理解等价表达式。", "math", ["math-concepts", "math-applications"], ["primary", "middle", "high"]],
  ["fraction-matcher", "分数配对", "匹配数字、图形和数轴上的分数表示。", "math", ["math-concepts"], ["primary", "middle"]],
  ["circuit-construction-kit-dc-virtual-lab", "直流电路虚拟实验室", "使用电池、导线和元件搭建并测量直流电路。", "physics", ["electricity-magnetism-circuits"], ["primary", "middle", "high"]],
  ["number-line-distance", "数轴：距离", "用数轴理解两点距离、绝对值和方向。", "math", ["math-concepts"], ["middle"]],
  ["ph-scale-basics", "pH值：基础", "比较常见液体的酸碱性，观察稀释对pH值的影响。", "chemistry", ["general-chemistry"], ["middle"]],
  ["area-model-algebra", "面积模型代数", "用面积模型展开、组合和因式分解代数式。", "math", ["math-concepts", "math-applications"], ["middle", "high"]],
  ["equality-explorer-two-variables", "等式探索：两个变量", "用平衡模型探索含两个变量的等式关系。", "math", ["math-applications"], ["middle", "high"]],
  ["molecule-shapes-basics", "分子形状：基础", "观察电子对排斥并预测常见分子的空间形状。", "chemistry", ["general-chemistry"], ["middle", "high"]],
  ["unit-rates", "单位比率", "比较不同情境中的单位比率、价格和速度。", "math", ["math-applications"], ["middle", "high"]],
  ["build-a-molecule", "创造一个分子", "组合原子构建常见分子并理解分子式。", "chemistry", ["general-chemistry"], ["middle", "high"]],
  ["diffusion", "扩散", "观察粒子随机运动和不同条件下的扩散过程。", "chemistry", ["general-chemistry"], ["middle", "high"]],
  ["function-builder", "函数构建器", "设计输入输出规则，探索函数组合和多种表示。", "math", ["math-applications"], ["middle", "high"]],
  ["graphing-slope-intercept", "绘图：斜率与截距", "改变斜率和截距，连接方程、表格与直线图像。", "math", ["math-applications"], ["middle", "high"]],
  ["molecules-and-light", "分子与光", "观察不同分子对光的吸收，理解光与物质相互作用。", "chemistry", ["general-chemistry", "quantum-chemistry"], ["middle", "high"]],
  ["plinko-probability", "二项分布弹珠台概率", "通过重复落球实验观察概率分布和随机变化。", "math", ["math-applications"], ["middle", "high"]],
  ["atomic-interactions", "原子的相互作用", "改变原子间距，观察吸引力、排斥力和势能。", "chemistry", ["quantum-chemistry"], ["high"]],
  ["circuit-construction-kit-ac", "电路组建实验：交流", "搭建交流电路，观察电压、电流和元件响应。", "physics", ["electricity-magnetism-circuits"], ["high"]],
  ["circuit-construction-kit-ac-virtual-lab", "交流电路虚拟实验室", "使用测量工具搭建和分析更完整的交流电路。", "physics", ["electricity-magnetism-circuits"], ["high"]],
  ["curve-fitting", "曲线拟合", "选择函数模型拟合数据，比较参数和残差。", "math", ["math-applications"], ["high"]],
  ["gravity-force-lab", "万有引力实验", "改变质量和距离，定量研究万有引力定律。", "physics", ["motion"], ["high"]],
  ["least-squares-regression", "最小二乘回归", "调整直线并观察残差平方和，理解线性回归。", "math", ["math-applications"], ["high"]],
  ["states-of-matter", "物质状态", "从粒子层面研究固体、液体、气体及相变。", "physics", ["heat"], ["high"]],
  ["trig-tour", "三角函数之旅", "连接单位圆、角度、坐标与三角函数图像。", "math", ["math-applications"], ["high"]],
  ["vector-addition", "向量相加", "用分量和图形方法进行二维向量加法。", "physics", ["motion"], ["high"]],
  ["vector-addition-equations", "向量的和：等式", "连接向量图、分量和代数等式，解决向量问题。", "physics", ["motion"], ["high"]],
  ["number-pairs", "数字配对（英文界面）", "用对象配对理解数字分解、组合和加减关系。", "math", ["math-concepts"], ["primary"], "en"],
  ["quadrilateral", "四边形（英文界面）", "拖动顶点比较四边形的边、角和平行关系。", "math", ["math-concepts"], ["primary", "middle"], "en"],
  ["center-and-variability", "数据中心与变异（英文界面）", "用可视数据探索中位数、范围和分布变化。", "math", ["math-applications"], ["middle"], "en"],
  ["mean-share-and-balance", "平均数：分享与平衡（英文界面）", "通过公平分享和平衡模型理解平均数。", "math", ["math-concepts", "math-applications"], ["middle"], "en"],
];

export const phetPhase3Simulations = phase3Rows.map(
  ([id, title, description, subject, topics, stages, locale = "zh_CN"]) => ({
    id,
    title,
    description,
    subject,
    topics,
    stages,
    localUrl: `/simulations/phet/${id}.html`,
    originalUrl: `https://phet.colorado.edu/${locale === "zh_CN" ? "zh_CN" : "en"}/simulations/${id}`,
    sourceUrl: `https://phet.colorado.edu/sims/html/${id}/latest/${id}_${locale}.html`,
    batch: "phase3",
    available: true,
  }),
);
