export const phetSubjectGroups = [
  {
    id: "physics",
    label: "物理",
    topics: [
      { id: "motion", label: "运动" },
      { id: "waves", label: "声音、振动、波" },
      { id: "work-energy-power", label: "功、能量、功率" },
      { id: "heat", label: "热学" },
      { id: "quantum-phenomena", label: "量子现象" },
      { id: "light-radiation", label: "光和辐射" },
      { id: "electricity-magnetism-circuits", label: "电场、磁场、电路" },
    ],
  },
  {
    id: "math",
    label: "数学",
    topics: [
      { id: "math-concepts", label: "数学概念" },
      { id: "math-applications", label: "数学的应用" },
    ],
  },
  {
    id: "chemistry",
    label: "化学",
    topics: [
      { id: "general-chemistry", label: "普通化学" },
      { id: "quantum-chemistry", label: "量子化学" },
    ],
  },
  {
    id: "earth-science",
    label: "地球科学",
    topics: [],
  },
  {
    id: "biology",
    label: "生物",
    topics: [],
  },
];

export const phetSchoolStages = [
  { id: "primary", label: "小学" },
  { id: "middle", label: "初中" },
  { id: "high", label: "高中" },
];

export const phetSimulations = [
  {
    id: "waves-intro",
    title: "波动入门",
    description: "通过水波、声波和光波观察频率与振幅的作用。",
    subject: "physics",
    topics: ["waves"],
    stages: ["primary", "middle"],
    localUrl: "/simulations/phet/waves-intro.html?locale=zh_CN",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/waves-intro",
    sourceUrl: "https://phet.colorado.edu/sims/html/waves-intro/latest/waves-intro_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "forces-and-motion-basics",
    title: "力和运动：基础",
    description: "通过拔河和推动物体探索力、摩擦与运动的关系。",
    subject: "physics",
    topics: ["motion"],
    stages: ["primary", "middle", "high"],
    localUrl: "/simulations/phet/forces-and-motion-basics.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/forces-and-motion-basics",
    sourceUrl: "https://phet.colorado.edu/sims/html/forces-and-motion-basics/latest/forces-and-motion-basics_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "projectile-motion",
    title: "斜抛运动",
    description: "改变发射角度、速度和空气阻力，观察抛体运动轨迹。",
    subject: "physics",
    topics: ["motion"],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/projectile-motion.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/projectile-motion",
    sourceUrl: "https://phet.colorado.edu/sims/html/projectile-motion/latest/projectile-motion_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "energy-skate-park",
    title: "能量滑板竞技场",
    description: "建造滑板轨道，观察动能、势能、热能与摩擦的变化。",
    subject: "physics",
    topics: ["work-energy-power"],
    stages: ["high"],
    localUrl: "/simulations/phet/energy-skate-park.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/energy-skate-park",
    sourceUrl: "https://phet.colorado.edu/sims/html/energy-skate-park/latest/energy-skate-park_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "masses-and-springs",
    title: "质量和弹簧",
    description: "改变质量、弹簧劲度和阻尼，研究振动、周期、力与能量。",
    subject: "physics",
    topics: ["motion", "work-energy-power"],
    stages: ["high"],
    localUrl: "/simulations/phet/masses-and-springs.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/masses-and-springs",
    sourceUrl: "https://phet.colorado.edu/sims/html/masses-and-springs/latest/masses-and-springs_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "pendulum-lab",
    title: "钟摆实验",
    description: "改变摆长、质量、重力和振幅，测量周期并观察能量变化。",
    subject: "physics",
    topics: ["motion", "work-energy-power"],
    stages: ["primary", "middle", "high"],
    localUrl: "/simulations/phet/pendulum-lab.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/pendulum-lab",
    sourceUrl: "https://phet.colorado.edu/sims/html/pendulum-lab/latest/pendulum-lab_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "states-of-matter-basics",
    title: "物质状态：基础",
    description: "加热、冷却和压缩粒子，观察固态、液态和气态的转变。",
    subject: "physics",
    topics: ["heat"],
    stages: ["primary", "middle", "high"],
    localUrl: "/simulations/phet/states-of-matter-basics.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/states-of-matter-basics",
    sourceUrl: "https://phet.colorado.edu/sims/html/states-of-matter-basics/latest/states-of-matter-basics_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "circuit-construction-kit-dc",
    title: "电路组建实验：直流",
    description: "搭建直流电路，使用电流表和电压表观察电路规律。",
    subject: "physics",
    topics: ["electricity-magnetism-circuits"],
    stages: ["primary", "middle", "high"],
    localUrl: "/simulations/phet/circuit-construction-kit-dc.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/circuit-construction-kit-dc",
    sourceUrl: "https://phet.colorado.edu/sims/html/circuit-construction-kit-dc/latest/circuit-construction-kit-dc_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "balloons-and-static-electricity",
    title: "气球和静电",
    description: "用气球探索电荷转移、静电吸引、排斥和电荷极化。",
    subject: "physics",
    topics: ["electricity-magnetism-circuits"],
    stages: ["primary", "middle", "high"],
    localUrl: "/simulations/phet/balloons-and-static-electricity.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/balloons-and-static-electricity",
    sourceUrl: "https://phet.colorado.edu/sims/html/balloons-and-static-electricity/latest/balloons-and-static-electricity_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "bending-light",
    title: "光的折射",
    description: "观察光在不同介质中的折射，使用棱镜探索色散和彩虹。",
    subject: "physics",
    topics: ["light-radiation"],
    stages: ["primary", "middle", "high"],
    localUrl: "/simulations/phet/bending-light.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/bending-light",
    sourceUrl: "https://phet.colorado.edu/sims/html/bending-light/latest/bending-light_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "color-vision",
    title: "光的混合",
    description: "混合红、绿、蓝光，观察波长、白光和颜色视觉的关系。",
    subject: "physics",
    topics: ["light-radiation"],
    stages: ["primary", "middle", "high"],
    localUrl: "/simulations/phet/color-vision.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/color-vision",
    sourceUrl: "https://phet.colorado.edu/sims/html/color-vision/latest/color-vision_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "john-travoltage",
    title: "静电电压",
    description: "通过日常场景观察静电积累、放电和人体受到电击的条件。",
    subject: "physics",
    topics: ["electricity-magnetism-circuits"],
    stages: ["primary", "middle", "high"],
    localUrl: "/simulations/phet/john-travoltage.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/john-travoltage",
    sourceUrl: "https://phet.colorado.edu/sims/html/john-travoltage/latest/john-travoltage_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "wave-interference",
    title: "波的干涉",
    description: "使用水波、声波和光波观察干涉、单缝衍射与双缝干涉。",
    subject: "physics",
    subjects: ["physics", "earth-science"],
    topics: ["waves", "light-radiation"],
    stages: ["primary", "middle", "high"],
    localUrl: "/simulations/phet/wave-interference.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/wave-interference",
    sourceUrl: "https://phet.colorado.edu/sims/html/wave-interference/latest/wave-interference_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "fractions-intro",
    title: "分数：入门",
    description: "通过图形、数值和游戏建立分数的基本概念。",
    subject: "math",
    topics: ["math-concepts"],
    stages: ["primary", "middle"],
    localUrl: "/simulations/phet/fractions-intro.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/fractions-intro",
    sourceUrl: "https://phet.colorado.edu/sims/html/fractions-intro/latest/fractions-intro_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "fractions-equality",
    title: "分数：等式",
    description: "使用不同分母构建等值分数，并通过图形和数字进行匹配。",
    subject: "math",
    topics: ["math-concepts"],
    stages: ["primary", "middle"],
    localUrl: "/simulations/phet/fractions-equality.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/fractions-equality",
    sourceUrl: "https://phet.colorado.edu/sims/html/fractions-equality/latest/fractions-equality_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "fractions-mixed-numbers",
    title: "分数：带分数",
    description: "使用图形和数字理解假分数、带分数及其相互转换。",
    subject: "math",
    topics: ["math-concepts"],
    stages: ["primary", "middle"],
    localUrl: "/simulations/phet/fractions-mixed-numbers.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/fractions-mixed-numbers",
    sourceUrl: "https://phet.colorado.edu/sims/html/fractions-mixed-numbers/latest/fractions-mixed-numbers_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "area-model-introduction",
    title: "面积模型入门",
    description: "构造不同尺寸的长方形，用面积模型理解乘法。",
    subject: "math",
    topics: ["math-concepts"],
    stages: ["primary"],
    localUrl: "/simulations/phet/area-model-introduction.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/area-model-introduction",
    sourceUrl: "https://phet.colorado.edu/sims/html/area-model-introduction/latest/area-model-introduction_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "number-line-operations",
    title: "数轴：运算",
    description: "在数轴上表示和计算正负数运算，观察位置与方向的变化。",
    subject: "math",
    topics: ["math-concepts"],
    stages: ["middle"],
    localUrl: "/simulations/phet/number-line-operations.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/number-line-operations",
    sourceUrl: "https://phet.colorado.edu/sims/html/number-line-operations/latest/number-line-operations_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "graphing-lines",
    title: "直线图形",
    description: "探索直线、斜率、截距、线性方程和图像之间的关系。",
    subject: "math",
    topics: ["math-applications"],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/graphing-lines.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/graphing-lines",
    sourceUrl: "https://phet.colorado.edu/sims/html/graphing-lines/latest/graphing-lines_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "build-an-atom",
    title: "原子模型",
    description: "使用质子、中子和电子构建原子，观察元素、电荷和质量变化。",
    subject: "chemistry",
    topics: ["general-chemistry"],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/build-an-atom.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/build-an-atom",
    sourceUrl: "https://phet.colorado.edu/sims/html/build-an-atom/latest/build-an-atom_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "balancing-chemical-equations",
    title: "配平化学方程式",
    description: "通过粒子模型和游戏理解并练习化学方程式配平。",
    subject: "chemistry",
    topics: ["general-chemistry"],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/balancing-chemical-equations.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/balancing-chemical-equations",
    sourceUrl: "https://phet.colorado.edu/sims/html/balancing-chemical-equations/latest/balancing-chemical-equations_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "molecule-shapes",
    title: "分子形状",
    description: "构建三维分子，探索化学键、孤对电子和分子空间结构。",
    subject: "chemistry",
    topics: ["general-chemistry"],
    stages: ["high"],
    localUrl: "/simulations/phet/molecule-shapes.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/molecule-shapes",
    sourceUrl: "https://phet.colorado.edu/sims/html/molecule-shapes/latest/molecule-shapes_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "concentration",
    title: "浓度",
    description: "改变溶质、水量和蒸发程度，观察并测量溶液浓度。",
    subject: "chemistry",
    topics: ["general-chemistry"],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/concentration.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/concentration",
    sourceUrl: "https://phet.colorado.edu/sims/html/concentration/latest/concentration_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "acid-base-solutions",
    title: "酸碱溶液",
    description: "测量溶液pH值和导电性，比较强弱酸碱及浓度的影响。",
    subject: "chemistry",
    topics: ["general-chemistry"],
    stages: ["high"],
    localUrl: "/simulations/phet/acid-base-solutions.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/acid-base-solutions",
    sourceUrl: "https://phet.colorado.edu/sims/html/acid-base-solutions/latest/acid-base-solutions_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "ph-scale",
    title: "pH值",
    description: "测试常见液体的pH值，观察酸碱性、稀释与离子数量变化。",
    subject: "chemistry",
    topics: ["general-chemistry"],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/ph-scale.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/ph-scale",
    sourceUrl: "https://phet.colorado.edu/sims/html/ph-scale/latest/ph-scale_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "natural-selection",
    title: "自然选择",
    description: "控制环境和兔子的遗传变异，探索自然选择规律。",
    subject: "biology",
    topics: [],
    stages: ["primary", "middle", "high"],
    localUrl: "/simulations/phet/natural-selection.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/natural-selection",
    sourceUrl: "https://phet.colorado.edu/sims/html/natural-selection/latest/natural-selection_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "gene-expression-essentials",
    title: "基因表达基础",
    description: "观察蛋白质合成过程，探索影响细胞基因表达的因素。",
    subject: "biology",
    topics: [],
    stages: ["high"],
    localUrl: "/simulations/phet/gene-expression-essentials.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/gene-expression-essentials",
    sourceUrl: "https://phet.colorado.edu/sims/html/gene-expression-essentials/latest/gene-expression-essentials_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "gravity-and-orbits",
    title: "重力和轨道",
    description: "移动太阳、地球、月球和空间站，观察引力与轨道变化。",
    subject: "earth-science",
    topics: [],
    stages: ["primary", "middle", "high"],
    localUrl: "/simulations/phet/gravity-and-orbits.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/gravity-and-orbits",
    sourceUrl: "https://phet.colorado.edu/sims/html/gravity-and-orbits/latest/gravity-and-orbits_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "density",
    title: "密度",
    description: "改变质量和体积，测量物体密度并探索浮沉现象。",
    subject: "earth-science",
    topics: [],
    stages: ["primary", "middle"],
    localUrl: "/simulations/phet/density.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/density",
    sourceUrl: "https://phet.colorado.edu/sims/html/density/latest/density_zh_CN.html",
    batch: "phase1",
    available: true,
  },
  {
    id: "under-pressure",
    title: "受到压力",
    description: "观察液体深度、重力、容器形状和密度对压力的影响。",
    subject: "earth-science",
    topics: [],
    stages: ["middle", "high"],
    localUrl: "/simulations/phet/under-pressure.html",
    originalUrl: "https://phet.colorado.edu/zh_CN/simulations/under-pressure",
    sourceUrl: "https://phet.colorado.edu/sims/html/under-pressure/latest/under-pressure_zh_CN.html",
    batch: "phase1",
    available: true,
  },
];
